---
title: "Exploring Gun Violence Trends in the United States"
author: "Yuelin Long (yl3181), Marisa Sobel (ms5533), Eileen Shea (eas2297), Zanis Fang (zf2213), Devon Morgan (dm3175)"
date: "12/3/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Motivation
Gun violence has been of increasing concern across the United States over the past decade. Our objective was to develop an online resource to explore general trends in gun violence and identify any important variables associated with gun violence incidence. The target audience for this webpage includes the general public, gun violence activists and legislators. This goal of this resource is to raise awareness on the widespread impact of gun violence, and inform future public health interventions and policy changes. 

## Related Work
Gun violence has received widespread media attention in recent years, particularly due to the increased occurrence of mass shootings. Preventing firearm injury and death has increasingly been considered a major public health issue.

Inspiration was drawn from a variety of background sources including:

*  [Gun Violence Archive](https://www.gunviolencearchive.org/), a nonprofit focused on providing data on gun related incidents in the U.S., which provides helpful visuals related to gun violence incidents across the country.
*  [Wintemute, G. J. (2015). The epidemiology of firearm violence in the twenty-first century United States. Annual Review of Public Health, 36, 5-19.](https://www.annualreviews.org/doi/full/10.1146/annurev-publhealth-031914-122535)
*  [Gun Violence - National Institute for Justice](https://www.nij.gov/topics/crime/gun-violence/pages/welcome.aspx) 
*  [Giffords Law Center](https://lawcenter.giffords.org)


The Data Science methods used for this project draw from topics covered throughout P8105. In particular, inspiration on some of the map visualizations was drawn from the in-class visualizations on the Airbnb dataset. Further, as a team comprised of biostatisticians, epidemiologists and environmental health scientists in training, we successfully drew from different areas of expertise to inform the direction of the project. 

## Initial Questions
Questions to address in the project include:

*  How do rates of gun violence differ across states? Which areas have the highest concentrations of gun violence? 
*  How have gun violence rates changed over time? 
*  Which age groups and races are most impacted by gun violence mortality, and has this changed over time? 
*  How does gun law strength relate to firearm mortality? How do gun law strengths differ across the U.S.?
*  How are unemployment rates related to firearm mortality? 
*  How are gun license approval rates related to firearm mortality and law strength? 
*  How does the gun application percentage(proportion of people applying for the license in total population) relate to firearm mortality and law strength? 

## Data Sources and Cleaning Method
Source, scraping method, cleaning, etc.

### Gun Violence Incident Data (Gun Violence Archive) 
Data on specific Gun Violence incidents throughout the U.S. was downloaded from a data repository [here](https://www.kaggle.com/jameslko/gun-violence-data), which pulls data from the [Gun Violence Archive](http://www.shootingtracker.com/), a "online archive of gun violence incidents collected from over 2,500 media, law enforcement, government and commercial sources daily in an effort to provide  near-real time data about the results of gun violence. GVA in an independent data collection and research group with no affiliation with any advocacy organization."

The dataset used from 

#### Cleaning


### CDC Firearm Mortality Data 
Data on Firearm Mortality was obtained from the [CDC Wonder data query](https://wonder.cdc.gov/ucd-icd10.html). The interface allows for selection of  relevant variables.

#### Cleaning

### Gun Law Strength and State Scoring
Data on 


#### Cleaning

***Gun law scores of states*** is created by the [Giffords Law Center](https://lawcenter.giffords.org/scorecard/#rankings) using "a comprehensive grading rubric that assigns positive point values to gun safety policies, such as private-sale background checks and extreme risk protection orders, and negative point values to dangerous laws, such as permitless concealed carry". 

### Gun Approval Rate and Liscensing of States


### 


The Github repository for this project can be found [here](https://github.com/ChristineLong/p8105_Final_Project). 

## Exploratory Analyses




Decided to use the data on firearm mortality from the CDC. 

Decided to not focus on subtypes of gun violence, including mass shootings versus domestic violence, but gun violence in general. We acknowledge that risk factors could differ across sub-types. Important to consider in the future -- 
overall 
 

## Regression Analyses 
### Section 4: Regression Analyses


## Discussion and Results

### Section 1: Overview of Gun Violence in United States



### Section 2: Exploration of Firearm Mortality in United States


Map visualizing the change in crude death rate over time (1999-2016) for each state. 

### Section 3: Role of Gun Control in Gun Violence




### Section 4: Regression Analyses
